language: java
script: mvn verify deploy --settings maven_deploy_settings.xml
jdk:
- oraclejdk7
- openjdk7
notifications:
  email:
    recipients:
    - yammer-sonatype@microsoft.com
env:
  global:
  - secure: KTTmV/3zurg43u7bPPfC73lK+XGVZZk40YPZmWnTuAYwLbWJYLrxPK7h39xLZhhYDE6+PTwFdseLAbGVYl7DZtHJYh4Lf1J2UOiIcs4w7+oxQeDpRebsUrro6yPcEOs7JYgUShgNqoQTNE1P9pcRzJYwdojKmbnWi9hwy3xfQdQ=
  - secure: DwO6aLe9ZJQ1mNAQwxl+yheQlJtbLmpEdVT9c+oQc4DTXiS3X1dz+9jdvgWfKDv+/VveoZrZK/1xvK1Qx8xptQQ+jN6fyBFuHy5CicxWGU781RqnVLCiteloVO+5/gdR5ewj0pyV85sW4mf5y3wY/wfHc3RuM+gGcdsq34+D9+g=
